commerce/auctions/urls.py
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


from . import views
from .views import index, login_view,logout_view,register
from .views import CreateListings_view, Listingspage_view,  Bids_view
from .views import Watchlist_view, Categories_view, CategoryShow_view


app_name = 'auctions'
urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('register', views.register, name='register'),

    path('index', views.index, name='index'),
    path('CreateListings', views.CreateListings_view, name='CreateListings'),
    path('Listingspage', views.Listingspage_view, name='Listingspage'),
    path('Bid/<str:Btitle>', views.Bids_view, name='BidsDetail'),
    path('Categories', views.Categories_view, name='Categories'),
    path('Category/<str:C_description>', views.CategoryShow_view, name='CategoryShow'),
    path('Watchlist', views.Watchlist_view, name='Watchlist'),




] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

commerce/auctions/templates/auctions/BidsDetail.html
{% extends "auctions/layout.html" %}

{% block title %}
    Bid Negociation

{% endblock %}

{% block body %}

<h2 style="text-align: center;">Bid´s Detail for: {{Btitle}} , {{user.username}}  </h2>
<h4 style="color:red;"> {{message}}</h4>
<hr>

<div class ="flex-container" style="text-align: center;">
    <div class="container" style="width:90%;">
        <div class="row"  width="1700px">
          {%for L in L_data %}
              <div class="col-lg-3">
                     <br>
                     <h3>{{L.Ltitle }}</h3>
                     <img src=" {{L.Limage.url}} "  width="200">
                     <br>
              </div>
              <br>
              <div class="col-lg-5">
              <br>
                     <h5>Auction Start Date  </h5>
                     <p>{{ L.Ldatestart }}</p>
                     <h5>Auction End Date  </h5>
                     <p>{{ L.Lduration }} Days</p>
                     <h5>Initial Price </h5>
                     <p> {{ L.Lprice |floatformat:2 }}</p>
                     <h5>Status</h5>
                     <p>{{ L.Lstatus }}</p>

              </div>
              <div class="col-lg-2">
                      <br>
                      <h5>Seller</h5>
                      <p>{{ L.Luser }}</p>
                      <br>
                      <h5>Description</h5>
                      <p>{{ L.Ldescription }}</p>
              </div>
              <div class="col-lg-2" style="border:double;border-color:#004d00 ;">
                <br>  <br>  <br>  <br>
                 {% if Status == "Sold" %}
                    <h5> Sold To: </h5>
                    <p>  {{Winner}} </p>
                    <p>  {{BestOffer|floatformat:2}} </p>
                    {% if Winner == user.username %}
                       <h3 style="background-color:#004d00;color:#e6ffe6 ;">   Congrats! you won the aution  </h3>
                    {%endif%}
                 {% else %}
                    <h5> Who is Winning? </h5>
                    <p>  {{Winner}} </p>
                    <p>  {{BestOffer|floatformat:2}} </p>

                {% endif %}
                  <br>
                  <br>
          {%endfor%}
        </div>
        <hr>
      </div>

    <hr>
    </div>


  <div class="container" style="border:#004d00; width:90%">
    <form action="{% url 'auctions:BidsDetail' Btitle %}" method="post">{% csrf_token %}
          <!--BID-->
        <div class="row"  width="1700px">
            <div class="col-lg-4" style=" border: 4px dotted #004d00 ;">
               <form class="form-control"  method="post" >{% csrf_token %}
                  <h5> Actual Bids </h5>
                  {% if B_data|length > 0 %}
                      {%for B in B_data %}
                          <p style='text-align: left;'>Date : {{B.Bdate |date:"Y-m-d"}} - User: {{B.Buser}}</p>
                          <p style='text-align: left;'>Offer: {{B.Bprice |floatformat:2 }}   </p>
                      {% endfor %}
                  {%else%}
                      <h5>This Listing doesn´t have Bids Yet </h5>
                  {%endif%}
                  <p style='color:red;'>{{msgbids}}</p>
                  <br>
                  {%if Status != "Sold" %}
                       <b >  {{ BidForm }}  </b>
                       <br> <br>
                       <p>
                       <button type="Submit" name="SubmitBid">Send your Offer</button>
                       </p>
                       <br>
                  {%endif%}
                </form>
            </div>

            <!--COMMENTS-->
            <div class="col-lg-4"   >
                <form class="form-control" method="post" style="border: 4px solid #004d00 ;">{% csrf_token %}
                <h5> Comments </h5>
                {%if C_data|length > 0 %}
                    {%for C in C_data %}
                       <p style='text-align: left;'> {{C.Cdate}} - <b>{{C.Cuser}}</b>-{{C.Ccomment}}</p>
                    {%endfor%}
                {%else%}
                      <h5>This listing doesn´t have any comments yet </h5>
                {%endif%}
                {%if Status != "Sold" %}
                   <b>   {{ CommentForm }}   </b>
                   <br>
                   <button type="Submit" name="SubmitComment">Send your comment</button>
                {% endif %}
                </form>
                <br>
            </div>

            <!--CHANGE STATUS-->
            <div class="col-lg-4" style=" border: 4px dotted #004d00 ;">
              <!--WATCH LIST-->
                  {% if W_data|length > 0 %}
                      {% for W in W_data %}
                         {% if W.user == user.username %}
                              <form method="post" >
                                  {% csrf_token %}
                                  <h5>Remove from Whatchlist?</h5>
                                  <br>
                                  <p> {{ RemoveWatch }}</p>

                                  <button type="Submit" class="btn btn-danger" name="Remove" value="0">
                                  Remove from Watch? <i class="fa fa-shopping-cart"></i></button>

                              </form >
                           {% endif %}
                       {% endfor %}
                    {% else %}
                          <form  method="post" >
                              {% csrf_token %}
                              <h5>Add To Whatchlist?</h5>
                              <br>
                              <p>{{ AddWatch }}</p>

                              <button type="Submit" class="btn btn-success" name="Add" value="1">
                              Add to Watch <i class="fa fa-shopping-cart"></i></button>

                          </form>
                     {% endif %}
                       <br>
              </form>
              <br>
              <form  method="post" >
                  {% csrf_token %}
                    {% for L in L_data %}
                        {% if user.username == L.Luser  %}
                          <b>
                          <b><p style="font-size:18px"> {{ChangeStatusForm}} </p></b>
                          <button type="Submit" name="SaveChange">Save New Status</button>
                          <br>
                        {% endif %}
                   {% endfor %}
              </form>


            </div>
        </div>
    </form>
  </div>





</div>
{% endblock %}

commerce/auctions/templates/auctions/Categories.html
{% extends "auctions/layout.html" %}

{% block title %}
    Categories

{% endblock %}

{% block body %}
<h2 style=" text-align: center;">Categories</h2>
<h4 style="color:red;"> {{message}}</h4>
<hr>


<div class="container" >
      {% if Categories|length > 0 %}
	        <div class="container" style="width:90%">
		          <div class="row" width="1000px;">
                  <div class="col-lg-4" style="position:relative; top:50px">
                      <br>
                      <h3>Choose a category</h3>
                      <br>
                      <h3>to see available itens:</h3>
                  </div>
                  <div class="col-lg-4" >
                    {% csrf_token %}

					              {% for Category in Categories %}
                           <br>
                            <h4><li style="background-color:#004d00 ; text-align: center; position:relative; top:30px">
                                <a style="color:#e6ffe6;" href= "{% url 'auctions:CategoryShow' C_description=Category.Cdescription  %}">
                                      {{ Category.Ccode }} - {{ Category.Cdescription }}</a>
                                </li><h4>        

				                {% endfor %}

                  </div>
                  <div class="col-lg-4">
                  </div>
			        </div
          </div>

        {% else %}
	         	<div class="form-group">
		          	<output><h1>No matches found</h1></output>
	        	</div>
	      {% endif %}

</div>




{% endblock %}

commerce/auctions/templates/auctions/CategoryShow.html
{% extends "auctions/layout.html" %}

{% block title %}
    {{C_description}}

{% endblock %}

{% block body %}

<h2 style=" text-align: center;">Active Listings by Category:   {{C_description}}</h2>
  <h4 style="color:red;"> {{message}}</h4>
  <hr>

<div class ="flex-container" style="width: 80%">
    <form  >
    {% csrf_token %}
    {% for C in C_data%}
        {%if C.Lstatus == "Active"%}
          <br>
            <div class="container" style="border:#004d00; width:90%">
                <br>
                <div class="row"  width="1700px">
                    <br>
                    <div class="col-lg-2">
                    </div>
                    <div class="col-lg-4">
                        <h3>{{ C.Ltitle }}</h3>
                        <img src=" {{C.Limage.url}} "  width="200">
                    </div>
                    <br>
                    <div class="col-lg-4">
                      <br>
                      <h5>Auction Start Date  </h5>
                      <p>{{ C.Ldatestart }}</p>
                      <h5>Initial Price </h5>
                      <p> {{ C.Lprice }}</p>
                      <h5>Description</h5>
                      <p>{{ C.Ldescription }}</p>
                    </div>
                    <div class="col-lg-2">
                      <h5>Seller</h5>
                      <p>{{ C.Luser }}</p>
                      <P>{{C_description}}</P>
                      <br>
                    </div>
                </div>
                <hr>
            </div>
        {%endif%}


    {%endfor%}
    </form>
</div>
{% endblock %}

commerce/auctions/templates/auctions/Listingspage.html
{% extends "auctions/layout.html" %}

{% block title %}
    Listing Page

{% endblock %}

{% block body %}
<h2 style=" text-align: center;">Listing Page the Bid´s Point</h2>
<h4 style="color:red;"> {{message}}</h4>
<hr>

<div class="form-group">
  <form >
      {% csrf_token %}
      {% if Listings|length > 0 %}
          {% for L in Listings %}
              <div class="container" style="border:#004d00; width:90%">
                  <div class="row"  width="1700px"  style="text-align: center;">
                      <div class="col-lg-3">
                            <h2>{{  L.Ltitle }}</h2>
                            <br>
                            <img src=" {{L.Limage.url}} "  width="200">
                            <br>
                      </div>
                      <div class="col-lg-6" >
                          <br><br>
                          <h5>Auction Start Date  </h5>
                          <p>{{  L.Ldatestart }}</p>
                          <h5>Initial Price </h5>
                          <p> {{  L.Lprice |floatformat:2 }}</p>

                          <h5>Description</h5>
                          <p>{{  L.Ldescription }}</p>
                          <h5>Seller:</h5>
                          <p>{{  L.Luser }}</p>
                      </div>
                      <div class="col-lg-3" >
                      <br>

                      <h5>Status</h5>
                      <h4 style="background-color:#004d00; color:#e6ffe6 ; align:center;">
                      {{  L.Lstatus}} </h4>
                      <br>
                      <br>

                      <br>
                          <p style="color:  #004d00; border:double;" >
                          <a href="{% url 'auctions:BidsDetail' Btitle=L.Ltitle%}" >
                          <h4>Go for Bid Details of listing:  {{  L.Ltitle }}</h4></a>
                          </p>




                      </div>
                  </div>
              </div>
              <hr>


          {% endfor %}
      {% else %}
            <div class="form-group">
                <output>No matches found</output>
            </div>
      {% endif %}
  </form>
</div>


{% endblock %}

commerce/auctions/templates/auctions/WatchList.html
{% extends "auctions/layout.html" %}

{% block title %}
    Watchlist

{% endblock %}

{% block body %}
<h2 style=" text-align: center;">Watchlist for: {{user.username}} </h2>
  <h4 style="color:red;"> {{message}}</h4>
  <hr>

<form action ="{% url 'auctions:Watchlist' %}">
  {% csrf_token %}
   	<div class="form-group" >

        <table class="table" width=50%>
            <thead>
		      	    <tr>
                <th </th>
                <th scope="col">Auction Title </th>
                <th scope="col">Status </th>
      	        </tr>
		        </thead>

            {% if Wishlists|length > 0  %}

	              {% for W in Wishlists %}
                  {%if user.username == W.user%}
                      <tr>
                      <td></td>
                      <td><a href="{% url 'auctions:BidsDetail' Btitle=W.Lcode.Ltitle %}">  {{W.Lcode.Ltitle}} </a> </td>
                      <td>  {{W.Lcode.Lstatus}} </td>

                      </tr>

                  {%endif%}
                {% endfor %}
            {% else %}
                 	<div class="form-group">
                      	<output><h1>No matches found for your Whatchlist   {{user.username}} </h1></output>
                        <input type="hidden" id="u" name="username" value={{user.username}}>
                	</div>
            {% endif %}


	      </table>
    </div>
</form>

{% endblock %}

commerce/auctions/templates/auctions/createlistings.html
{% extends "auctions/layout.html" %}

{% block title %}
    New Auction List

{% endblock %}

{% block body %}
<h2 style=" text-align: center;">Create a new Listing:</h2>
  <h4 style="color:red;"> {{message}}</h4>
  <hr>
<p style="color: red;text-align: center;">Fields with * are required to save the listing.<p>

<p>{{message}}<p>

<div class ="flex-container" style="width: 80%">
    <form  action= "{% url 'auctions:CreateListings' %}" method="post" >

        {% csrf_token %}

        <div class="container">
          <div class="row">
            <div class="col-lg-2">
            </div>
            <div class="col-lg-3">
                <label for="Ltitle" ><b>Title for the auction item : *</b>
                <input type="text" class="form-inline" id="Ltitle" name="Ltitle" required></label>
            </div>
            <div class="col-lg-3">
                <label for="Lprice" ><b>Start Price : *</b>
                <input type="text" class="form-inline" id="Lprice" name="Lprice" required></label>
            </div>
            <div class="col-lg-3">
                <label for="Ccode" ><b>Select the Category: *</b>
                  <select  class="form-control" id="Ccode" name="Ccode">
                      {% for Category in Categories %}
                          <option id="Ccode" name="Ccode" value= "{{ Category.Ccode }}" >  {{ Category.Ccode }} - {{ Category.Cdescription }}</option>
                      {% endfor %}
                  </select>
                </label>
            </div>

          </div>
        </div>
        <br>
        <div class="container">
           <div class="row">
             <div class="col-lg-2">
             </div>
             <div class="col-lg-8">
             <p><label for="Ldescription"><b>Describe de Item do be sold : *</b></label></p>
             <textarea  type="text" id="Ldescription" name="Ldescription" rows="6" cols="105" required ></textarea>
             </div>
             <div class="col-lg-2">
             </div>
          </div>
        </div>
        <br>

        <div class="container">
          <div class="row">
            <div class="col-lg-2">
            </div>
            <div class="col-lg-3">
                <label for="Ldatestart"><b>Date for Auction starts : *</b>
                <input type="text" class="form-inline" id="Ldatestart" name="Ldatestart" placeholder=YYYY-MM-DD required>{{d}}</label>
            </div>
            <div class="col-lg-3">
                <label for="Lduration"><b>Deadline to close (in days)? *</b>
                <input type="text" class="form-inline" id="Lduration" name="Lduration" required></label>
            </div>
            <div class="col-lg-4">
                <label for="Luser"><b>Advertiser user : *</b>
                <input type="text" class="form-inline"  id="Luser" name="Luser" value="{{ user.username }}" required> </label>
            </div>

          </div>
        </div>
        <br>

        <div class="container">
          <div class="row">
            <div class="col-lg-2">
            </div>
            <div class="col-lg-2">
                <label for="Lstatus"><b>Status : *</b>
                <select name="Lstatus" id="Lstatus" name="Lstatus">
                    <option value="Active">Active </option>
                    <option value="To Begin">To Begin </option>
                    <option value="Closed">Closed </option>
                    <option value="Sold">Sold </option>
               </select></label>
            </div>
            <br><br>
            <div class="col-lg-5">
               <p><b>Click on the "Choose File" button to upload a Picture:</b></p>
               <input type="file" id="Limage" name="Limage">
            </div>
            <div class="col-lg-3">
                <form class="form-inline" style="position:relative; top:100px">
                    <button type="submit" class="btn btn-success">Save</button>
                    <button type="button" class="btn btn-danger"><a href="{% url 'auctions:index' %}">Cancel</button>
               </form>
            </div>

    </form>
</div>


{% endblock %}

commerce/auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}

  <h2 style=" text-align: center;">Active Listings</h2>
  <h4 style="color:red;"> {{message}}</h4>
  <hr>

    <div class="form-group" >
      <form >
          {% csrf_token %}
          {% if ActiveListings|length > 0 %}
              {% for Active in ActiveListings %}
                    {%if Active.Lstatus == "Active"%}

                        <div class="container" style="border:#004d00; width:90%">
                            <div class="row"  width="1700px">
                                <div class="col-lg-2">
                                </div>
                                <div class="col-lg-4">
                                    <h3>{{ Active.Ltitle }}</h3>
    		                            <img src=" {{Active.Limage.url}} "  width="200">
                                    <br>
                                </div>
                                <div class="col-lg-4">
                                  <br>
                                  <h5>Auction Start Date  </h5>
                                  <p>{{ Active.Ldatestart }}</p>
                                    <h5>Initial Price </h5>
                                    <p> {{ Active.Lprice }}</p>

                       	          <h5>Description</h5>
    					        	          <p>{{ Active.Ldescription }}</p>
                                </div>
                                <div class="col-lg-2">
                                </div>
                            </div>
                            <hr>
                        </div>
                    {%endif%}
    				  {% endfor %}
          {% else %}
    	         	<div class="form-group">
    		          	<output>No matches found</output>
    	        	</div>
          {% endif %}
    	</form>
    </div>


{% endblock %}

commerce/auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link type="text/css" href="{% static 'auctions/styles.css' %}" rel="stylesheet">
        <link type="image" href="{% static 'images/Mural.jpg' %}" rel="stylesheet">

        <style>
          body {
            padding: 10px;
            color:  #004d00 ;
            background-color:  #00cc99;
            background-image: linear-gradient(to top left,  #00cc99, #b3ffec, white );
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
            height: 100%;

            }
        </style>
    </head>
    <body>

        <div class="row" >
            <div class="col-lg-3" style="background-color:#004d00;color:#e6ffe6 ;">
                <h1 style="text-align: center;">Auctions</h1>
                {% if user.is_authenticated %}
                    <p style="text-align: center;">Signed in as <strong >{{ user.username }}</strong>.</p>
                {% else %}
                    <p style="text-align: center;">Not signed in.</p>
                {% endif %}
            </div>
            <div class="col-lg-8" >
                <ul class="nav">

                <li class="nav-item"><br>
                  <a  style="color:  #004d00;" class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item"><br>
                    <a  style="color:  #004d00;" class="nav-link" href="{% url 'auctions:CreateListings' %}">Create Listing</a>
                    </li>
                    <li class="nav-item"><br>
                    <a  style="color:  #004d00;" class="nav-link" href="{% url 'auctions:Watchlist' %}">Watchlist</a>
                    </li>
                    <li class="nav-item"><br>
                    <a  style="color:  #004d00;" class="nav-link" href="{% url 'auctions:Categories' %}">Categories</a>
                    </li>

                    <li class="nav-item"><br>
                    <a  style="color:  #004d00;" class="nav-link" href="{% url 'auctions:Listingspage' %}">Listings Page or Bid´s Page</a>
                    </li>
                    <li class="nav-item"><br>
                    <a  style="color:  #004d00;" class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
                    </li>
                {% else %}
                    <li class="nav-item"><br>
                        <a  style="color:  #004d00;" class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
                    </li>
                    <li class="nav-item"><br>
                        <a  style="color:  #004d00;" class="nav-link" href="{% url 'auctions:register' %}">Register</a>
                    </li>
                {% endif %}

                </ul>
            </div>
            <div class="col-lg-1" >
                <p> {{Today}} </p>
            </div>
        </div>

      <hr>
      <div class="BackImg">

      </div>

      {% block body %}
      {% endblock %}
    </body>
</html>

commerce/auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2 style="text-align: center;">Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:login' %}" method="post" >
        {% csrf_token %}
        <div class ="flex-container" style="text-align: center;">
            <br><br>
            <div class="form-group" style="margin:auto; width: 50%;" >
                <input  autofocus class="form-control" type="text" name="username" placeholder="Username">
            </div>
            <br>
            <div class="form-group" style="margin:auto; width: 50%;" >
                <input  class="form-control" type="password" name="password" placeholder="Password">
            </div>
            <br>
            <br>
            <div class="form-group" style="align-items: center;" >
                <input class="btn btn-primary" type="submit"  value="Login">     Don't have an account?
                <a  href="{% url 'auctions:register' %}">Register here.</a>
             </div>
        </div>
    </form>


{% endblock %}

commerce/auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2  style="text-align: center;">Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:register' %}" method="post">
        {% csrf_token %}
        <div class ="flex-container" style="text-align: center;">
            <br>
            <div class="form-group" style="margin:auto; width: 50%;">
                <input class="form-control" autofocus type="text" name="username" placeholder="Username">
            </div>
            <br>
            <div class="form-group" style="margin:auto; width: 50%;">
                <input class="form-control" type="email" name="email" placeholder="Email Address">
            </div>
            <br>
            <div class="form-group" style="margin:auto; width: 50%;">
                <input class="form-control" type="password" name="password" placeholder="Password">
            </div>
            <br>
            <div class="form-group" style="margin:auto; width: 50%;">
                <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
            </div>
            <br>
                <input class="btn btn-primary" type="submit" value="Register">    Already have an account?
            <a href="{% url 'auctions:login' %}">Log In here.</a>
        </div>
        <br>
    </form>



{% endblock %}